version: "3"
services:

  # nginx:
  #   image: nginx:alpine
  #   volumes:
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - .:/src
  #   ports:
  #     - 8080:80

  php:
    container_name: my_php
    build:
      context: ./dockerfile
      dockerfile: php.dockerfile
    volumes:
      - .:/src

  composer:
    container_name: my_composer
    build:
      context: ./dockerfile
      dockerfile: composer.dockerfile
    volumes:
      - .:/src

  postgres:
    build:
      context: ./dockerfile
      dockerfile: postgres.dockerfile
    container_name: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  adminer:
    build:
      context: ./dockerfile
      dockerfile: adminer.dockerfile
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./src:/var/www/html
    ports:
      - 8081:8080
